{% set name = "wikipedia-api" %}
{% set version = "0.8.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: b31e93b3f5407c1a1ba413ed7326a05379a3c270df6cf6a211aca67a14c5658b

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - requests

test:
  imports:
    - wikipediaapi
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/martin-majlis/Wikipedia-API
  summary: Python Wrapper for Wikipedia
  description: |
    Wikipedia-API is easy to use Python wrapper for Wikipedias' API. It supports
    extracting texts, sections, links, categories, translations, etc from Wikipedia.
    Documentation provides code snippets for the most common use cases.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
    - martin-majlis
